1) what is numpy? 

NumPy, which stands for "Numerical Python," is a fundamental library in the Python programming language for scientific computing and numerical operations. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays efficiently.

2) different way to create an array in numpy

In [2]:
import numpy as np

In [7]:
# 1) from list
arr=np.array([1,2,3,4,5],dtype=float)

In [10]:
# 2)
arr=np.zeros((3,3),dtype=float)


In [13]:
# 3)
arr=np.ones((3,3),dtype=int)

In [15]:
# 4)
arr=np.full((3,3),5)

In [23]:
# 5)
arr=np.arange(1.2,10.2,0.5)

In [28]:
# 6)
arr=np.linspace(0,1,5)
arr=np.logspace(0,1,5)

In [62]:
#8)
np.random.seed(0)
arr=np.random.random((3,3))
arr2=np.random.rand(3,3)
arr3=np.random.randn(3,3)
arr4=np.random.randint((3,3))
# randn is follow standard normal distribuion

In [59]:
# 10)
arr=np.eye(3)
arr2=np.diag(np.array([1,2,3]))
arr3=np.empty((3,3))

3) ATTRIBUTES

In [74]:
np.random.seed(0)
arr=np.random.randint(1,10,(3,3))
arr

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [82]:
# 1)
arr.ndim
# 2)
arr.shape
# 3)
arr.size
# 4)
arr.dtype
arr.itemsize
arr.nbytes


72

4)ARRAY SLICING

In [86]:
np.random.seed(0)
arr=np.random.randint(1,10,(3,3))

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [109]:
# 1) 1D array slicing
x=np.array([1,2,3,4])
sub=x[:3]
# 1) 2D array slicing
s=arr[0,[1,2]] #simply
s=arr[1:,:1]   #row , column
s=arr[::2,::2] #step

5)CONCATINATION AND STACKING

#concatination 1d array
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

#concatination 2d array
grid=np.array([[1,2,3],[4,5,6]])
new_grid=np.concatenate([grid,grid],axis=1)


In [19]:
#stack @imp
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.stack([x,y],axis=1)
# array([[1, 3],
#        [2, 2],
#        [3, 1]])

#vstack @working with mixed dim
a=np.array([1,2,3])
grid=np.array([[4,5,6],
               [7,8,9]])
v=np.vstack([a,grid])


In [26]:
#hstack @working with mixed dim
grid=np.array([[4,5,6],
               [7,8,9]])

b=np.array([[99],
            [99]])
h=np.hstack([grid,b])
h


array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

# 6)spliting syn- np.split(arr,section or indices,axis)

In [47]:
arr1=np.array([1,2,3,4,5,6])
a1=np.split(arr1,2)
a11=np.split(arr1,(1,3))

arr2=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
a2=np.split(arr2,6,axis=1)

In [64]:
# vsplit and hsplit
grid=np.arange(16).reshape((4,4))
upper,lower=np.vsplit(grid,2)
left,right=np.hsplit(grid,2)
# samething
v=np.split(grid,2) #vsplit
h=np.split(grid,2,axis=1) #hsplit

7)MATH FUNCTIONS

In [86]:
# ARITHEMETIC FUNCTIONS
arr=np.array([1,2])
arr+5 #np.add()
arr-5 #np.substract()
arr*5 #...
arr/5
arr%5
arr**2 #np.power()
np.exp(arr)
~arr
arr<2 #filtering


array([ True, False])

ADVANCED MATH FUNCTIONS

In [82]:
# Create two NumPy arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A @ B  # This is equivalent to np.dot(A, B) or A.dot(B)

In [6]:
arr=np.array([1,2])
np.sqrt(arr)
np.log10(arr)
np.exp(arr)

np.sin(arr)
np.cos(arr)
np.tan(arr)

array([ 1.55740772, -2.18503986])

In [8]:
# Statitical function
arr=np.array([1,2,1])
np.min(arr)
np.max(arr)
np.mean(arr)
np.median(arr)
np.var(arr)
np.std(arr)

0.4714045207910317

8) Broadcasting

In [17]:
arr=np.zeros((3,3))
b=np.array([[1,2,3]])#to get transpose we need to intialize it as 2D
arr+5
arr+b
arr+b.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

9) ARRAY MANIPULATIONS

In [52]:
# 1)reshaepe()
arr=np.arange(16)
arr=arr.reshape(4,4)
# 2)np.transpose
arr=np.transpose(arr)
# 3)flatten()
arr=arr.flatten()

# 4)expand_dims ,1d to 2d or 2d to 3d
np.expand_dims(arr,axis=0) 
# array([[ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15]])
arr=np.expand_dims(arr,axis=1)
# array([[ 0],
#        [ 4],
#        [ 8],.....

# 5)squeeze ,2d to 1d or 3d to 2d
arr=np.array([[ 0],
          [ 4],
          [ 8],])
np.squeeze(arr)

In [56]:
# 6)repeat 
arr1=np.array([1,2,3,4,5])
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [59]:
#7)roll
arr=np.array([1,2,3,4,5])
np.roll(arr,2)

array([4, 5, 1, 2, 3])

In [60]:
# 8)np.sort()
# 9)searchsort() # gives pos where a mentioned element can insert inorder to mantain order
# 10)np.count()
# 11)np.count_nonzero()
# 12)np.where(arr>0) # gives indices where non_zero element exists
# 13)extract(arr>2,arr)# gives new array with elements >2 from mentioned array
# 15)np.copy() #deep copy
# 16)np.view() #shallow copy / =


10)String functions

In [61]:
# np.char.upper()
# np.char.capitilize()
# np.char.title()

11) some other functions

In [63]:
np.fromfunction( lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [65]:
np.fromiter((1,2,3),float)

array([1., 2., 3.])

In [67]:
np.fromstring('1 2 3',sep=' ')

array([1., 2., 3.])

12) MATRIX

In [3]:
l=[1,2,3,4,5]
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [5]:
m=np.matrix(l) # 2d array or matrix
m

matrix([[1, 2, 3, 4, 5]])

In [7]:
np.asanyarray(m)#not converted bcz matrix is also a type of array

matrix([[1, 2, 3, 4, 5]])

13) make pandas data frame from ndarray

In [8]:
import pandas as pd

In [12]:
arr=np.eye(3)
pd.DataFrame(arr)

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

14) loadtxt and savetxt

15)iterate though matrix

In [20]:
a=np.arange(16).reshape((4,4))
for cell in a.flatten():
    print(cell)
print()
for cell in np.nditer(a,order='F'):
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15
